name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Install Chrome browser
      uses: browser-actions/setup-chrome@v1

    - name: Build and run tests
      run: mvn test

    - name: Send Email Notification
      if: always()  # Run this step regardless of test result (success or failure)
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_EMAIL }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "Selenium Test Results - ${{ github.workflow }} (Run #${{ github.run_number }})"
        to: "etornam.koko@amalitech.com"
        from: "GitHub Actions <${{ secrets.SMTP_EMAIL }}>"
        body: |
          **Repository**: ${{ github.repository }}
          **Branch**: ${{ github.ref }}
          **Commit**: ${{ github.sha }}
          **Status**: ${{ job.status }}

        Check full logs here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: Send Slack Notification
      if: always()
      run: |
        STATUS="${{ job.status }}"
        if [ "$STATUS" == "success" ]; then
          message="✅ *Tests Passed!* ✅"
        else
          message="❌ *Tests Failed!* ❌"
        fi
    
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\":\"$message\nRepo: $GITHUB_REPOSITORY\nCommit: $GITHUB_SHA\nTrigger: $GITHUB_EVENT_NAME\nCheck logs: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" \
        ${{ secrets.SLACK_WEBHOOK_URL }}